//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IneffableEntities : DbContext
    {
        public IneffableEntities()
            : base("name=IneffableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artikl> artikls { get; set; }
        public virtual DbSet<dobavljac> dobavljacs { get; set; }
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<kupac> kupacs { get; set; }
        public virtual DbSet<racun> racuns { get; set; }
        public virtual DbSet<radni_nalog_servisa> radni_nalog_servisa { get; set; }
        public virtual DbSet<rezervacija> rezervacijas { get; set; }
        public virtual DbSet<stavka_racuna> stavka_racuna { get; set; }
        public virtual DbSet<uloga> ulogas { get; set; }
        public virtual DbSet<zahtjev_za_servis> zahtjev_za_servis { get; set; }
    }
}
