//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class zahtjev_za_servis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zahtjev_za_servis()
        {
            this.radni_nalog_servisa = new HashSet<radni_nalog_servisa>();
        }
    
        public int zahtjev_id { get; set; }
        public Nullable<System.DateTime> datum_podnosenja { get; set; }
        public string opis { get; set; }
        public string status { get; set; }
        public int kupac_id { get; set; }
        public string naziv_uredjaja { get; set; }
        public string tip_uredjaja { get; set; }
        public string proizvodjac { get; set; }
        public string obavijest { get; set; }
        public string obrazlozenje { get; set; }
        public string procitano { get; set; }
    
        public virtual kupac kupac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<radni_nalog_servisa> radni_nalog_servisa { get; set; }
    }
}
