//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudArtikala
{
    using System;
    using System.Collections.Generic;
    
    public partial class radni_nalog_servisa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public radni_nalog_servisa()
        {
            this.racun = new HashSet<racun>();
        }
    
        public int servis_id { get; set; }
        public string oznaka { get; set; }
        public string uredjaj { get; set; }
        public int zaposlenik_id { get; set; }
        public string opis { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> vrijeme_kreiranja { get; set; }
        public int osoba_id { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual kupac kupac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racun> racun { get; set; }
    }
}
