//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudArtikala
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavka_racuna
    {
        public int racun_id { get; set; }
        public int artikl_id { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<double> cijena { get; set; }
    
        public virtual artikl artikl { get; set; }
        public virtual racun racun { get; set; }
    }
}
